### ISSUE TITLE
can't add repsitories

### ISSUE THREAD

**Issue by steveklabnik** [travis-ci/travis-watcher-macosx#9]
When I click plus, type something in and hit 'add', nothing shows up in the list. :(

I'm on 10.8.2. Let me know what else I can do to help.

**Comment by sarahhodne** [comment]
A few people on Twitter notified me about this. It's fixed in master, I'm about to upload a new version.

**Comment by steveklabnik** [comment]
What service!

**Comment by sarahhodne** [comment]
I just uploaded v0.2.3. Try that and please let me know if you're still seeing any issues.

**Comment by steveklabnik** [comment]
Totally works. Thanks! :heart:
